<a href="https://colab.research.google.com/github/ANILNbc2/ScalerAIMLCourse/blob/main/AIML_July_lecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# reversing an array
arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [ ]:
# Take a sample of 50 restaurants
sample_votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402, 150, 164, 424, 918, 90, 133, 144, 93, 62, 180, 62, 148, 219, 506, 172, 415, 230, 1647, 4884, 133, 286, 540, 2556, 36, 244, 804, 679, 245, 345, 618, 1047, 627, 354, 244, 163, 808, 1720, 868, 520, 299])
sample_costs = np.array([800.0, 800.0, 800.0, 300.0, 600.0, 600.0, 600.0, 700.0, 550.0, 500.0, 600.0, 500.0, 450.0, 800.0, 650.0, 800.0, 700.0, 300.0, 400.0, 500.0, 600.0, 550.0, 600.0, 500.0, 750.0, 500.0, 650.0, 600.0, 750.0, 200.0, 500.0, 800.0, 600.0, 400.0, 300.0, 450.0, 850.0, 300.0, 400.0, 750.0, 450.0, 450.0, 800.0, 800.0, 800.0, 850.0, 400.0, 1200.0, 300.0, 300.0])

# Create a 2D array: rows = restaurants, columns = [votes, costs]
restaurants_data = np.column_stack((sample_votes, sample_costs))

print("2D Array (votes, costs):\n", restaurants_data)
print("Shape:", restaurants_data.shape)
print("Dimensions:", restaurants_data.ndim)  # 2D

2D Array (votes, costs):
 [[ 775.  800.]
 [ 787.  800.]
 [ 918.  800.]
 [  88.  300.]
 [ 166.  600.]
 [ 286.  600.]
 [2556.  600.]
 [ 324.  700.]
 [ 504.  550.]
 [ 402.  500.]
 [ 150.  600.]
 [ 164.  500.]
 [ 424.  450.]
 [ 918.  800.]
 [  90.  650.]
 [ 133.  800.]
 [ 144.  700.]
 [  93.  300.]
 [  62.  400.]
 [ 180.  500.]
 [  62.  600.]
 [ 148.  550.]
 [ 219.  600.]
 [ 506.  500.]
 [ 172.  750.]
 [ 415.  500.]
 [ 230.  650.]
 [1647.  600.]
 [4884.  750.]
 [ 133.  200.]
 [ 286.  500.]
 [ 540.  800.]
 [2556.  600.]
 [  36.  400.]
 [ 244.  300.]
 [ 804.  450.]
 [ 679.  850.]
 [ 245.  300.]
 [ 345.  400.]
 [ 618.  750.]
 [1047.  450.]
 [ 627.  450.]
 [ 354.  800.]
 [ 244.  800.]
 [ 163.  800.]
 [ 808.  850.]
 [1720.  400.]
 [ 868. 1200.]
 [ 520.  300.]
 [ 299.  300.]]
Shape: (50, 2)
Dimensions: 2


In [ ]:
restaurants_data[:5,:]

array([[775., 800.],
       [787., 800.],
       [918., 800.],
       [ 88., 300.],
       [166., 600.]])

In [ ]:
# get 4th to 10 row of 2nd column
print(restaurants_data[3:10,1])
print(restaurants_data[3:10,1:])

array([[300.],
       [600.],
       [600.],
       [600.],
       [700.],
       [550.],
       [500.]])

# Aggregate functions

In [ ]:
restaurants_data

array([[ 775.,  800.],
       [ 787.,  800.],
       [ 918.,  800.],
       [  88.,  300.],
       [ 166.,  600.],
       [ 286.,  600.],
       [2556.,  600.],
       [ 324.,  700.],
       [ 504.,  550.],
       [ 402.,  500.],
       [ 150.,  600.],
       [ 164.,  500.],
       [ 424.,  450.],
       [ 918.,  800.],
       [  90.,  650.],
       [ 133.,  800.],
       [ 144.,  700.],
       [  93.,  300.],
       [  62.,  400.],
       [ 180.,  500.],
       [  62.,  600.],
       [ 148.,  550.],
       [ 219.,  600.],
       [ 506.,  500.],
       [ 172.,  750.],
       [ 415.,  500.],
       [ 230.,  650.],
       [1647.,  600.],
       [4884.,  750.],
       [ 133.,  200.],
       [ 286.,  500.],
       [ 540.,  800.],
       [2556.,  600.],
       [  36.,  400.],
       [ 244.,  300.],
       [ 804.,  450.],
       [ 679.,  850.],
       [ 245.,  300.],
       [ 345.,  400.],
       [ 618.,  750.],
       [1047.,  450.],
       [ 627.,  450.],
       [ 354.,  800.],
       [ 24

In [ ]:
np.sum(restaurants_data[:,0])

np.float64(30583.0)

In [ ]:
restaurants_data[:,0].sum()

np.float64(30583.0)

In [ ]:
#average cost of 10 restaurants
restaurants_data[:10,1].mean()

np.float64(625.0)

In [ ]:
# min and max vote
print(restaurants_data[,0].min())
print(restaurants_data[:,0].max())

36.0
4884.0


In [ ]:
data = np.arange(12).reshape(3, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(data, axis=0)

array([12, 15, 18, 21])

In [ ]:
np.sum(data,axis=1)

array([ 6, 22, 38])

#Logical Operators

In [ ]:
np.where(sample_costs > 700)

(array([ 0,  1,  2, 13, 15, 24, 28, 31, 36, 39, 42, 43, 44, 45, 47]),)

In [ ]:
sample_costs[np.where(sample_costs > 700)]

array([ 800.,  800.,  800.,  800.,  800.,  750.,  750.,  800.,  850.,
        750.,  800.,  800.,  800.,  850., 1200.])

In [ ]:
sample_costs[np.where((sample_costs > 500) & (sample_costs < 1000))]

array([800., 800., 800., 600., 600., 600., 700., 550., 600., 800., 650.,
       800., 700., 600., 550., 600., 750., 650., 600., 750., 800., 600.,
       850., 750., 800., 800., 800., 850.])

In [ ]:
True and False

False

In [ ]:
# Are there any restaurants with cost > 3000?
np.any(sample_costs > 800)

np.True_

In [ ]:
# Are all restaurants with cost > 800?
np.all(sample_costs > 800)

np.False_

In [ ]:
np.all(sample_costs > 100)

np.True_

In [ ]:

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])
rate = np.array([4.1, 3.8, 4.0, 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

print("Votes (Array):", votes)
print("Costs (Array):", costs)
print("Ratings (Array):", rate)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]
Ratings (Array): [4.1 3.8 4.  2.6 1.1 3.5 4.7 2.5 2.8 3.4]


In [ ]:

# Your numeric_data array
numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])

# Just to display in a good way
# Set print options to suppress scientific notation
np.set_printoptions(suppress=True, precision=1)

# Print the array
print("Numeric data (formatted):")
print(numeric_data)

Numeric data (formatted):
[[   4.1  775.   800. ]
 [   3.8  787.   800. ]
 [   4.   918.   800. ]
 [   2.6   88.   300. ]
 [   1.1  166.   600. ]
 [   3.5  286.   600. ]
 [   4.7 2556.   600. ]
 [   2.5  324.   700. ]
 [   2.8  504.   550. ]
 [   3.4  402.   500. ]]


In [ ]:
np.sort(votes)

array([  88,  166,  286,  324,  402,  504,  775,  787,  918, 2556])

In [ ]:
np.argsort(votes)

array([3, 4, 5, 7, 9, 8, 0, 1, 2, 6])

In [ ]:
array_2d = np.array([[34, 11, 8],
                     [7, 45, 18],
                     [9, 23, 20]])

np.sort(array_2d)

array([[ 8, 11, 34],
       [ 7, 18, 45],
       [ 9, 20, 23]])

In [ ]:
np.sort(array_2d, axis=0)

array([[ 7, 11,  8],
       [ 9, 23, 18],
       [34, 45, 20]])

# Matrix Operations

In [ ]:
votes * rate # element-wise multiplication

array([ 3177.5,  2990.6,  3672. ,   228.8,   182.6,  1001. , 12013.2,
         810. ,  1411.2,  1366.8])

In [ ]:
votes * 2

array([1550, 1574, 1836,  176,  332,  572, 5112,  648, 1008,  804])

In [ ]:
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])

In [ ]:
numeric_data

array([[   4.1,  775. ,  800. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   2.6,   88. ,  300. ],
       [   1.1,  166. ,  600. ],
       [   3.5,  286. ,  600. ],
       [   4.7, 2556. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ]])

In [ ]:
# method 1
np.dot(numeric_data, transformation_matrix)

array([[ 952.4, 1645.8, 2217.1],
       [ 958.1, 1663.5, 2228.9],
       [1023.8, 1860.2, 2360. ],
       [ 257.1,  314.1,  629.3],
       [ 504.3,  609.9, 1246.5],
       [ 567.2,  791.8, 1367.8],
       [1703.6, 4197.8, 3638.3],
       [ 655. ,  908. , 1585.2],
       [ 640.4, 1088.2, 1495.4],
       [ 555.1,  905.7, 1303.7]])

In [ ]:
# method 2
np.matmul(numeric_data, transformation_matrix)

array([[ 952.4, 1645.8, 2217.1],
       [ 958.1, 1663.5, 2228.9],
       [1023.8, 1860.2, 2360. ],
       [ 257.1,  314.1,  629.3],
       [ 504.3,  609.9, 1246.5],
       [ 567.2,  791.8, 1367.8],
       [1703.6, 4197.8, 3638.3],
       [ 655. ,  908. , 1585.2],
       [ 640.4, 1088.2, 1495.4],
       [ 555.1,  905.7, 1303.7]])

In [ ]:
# method 3
numeric_data @ transformation_matrix

array([[ 952.4, 1645.8, 2217.1],
       [ 958.1, 1663.5, 2228.9],
       [1023.8, 1860.2, 2360. ],
       [ 257.1,  314.1,  629.3],
       [ 504.3,  609.9, 1246.5],
       [ 567.2,  791.8, 1367.8],
       [1703.6, 4197.8, 3638.3],
       [ 655. ,  908. , 1585.2],
       [ 640.4, 1088.2, 1495.4],
       [ 555.1,  905.7, 1303.7]])

In [ ]:
a = np.array([1,2,3,4])

a@5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
a @ np.array([5])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [ ]:
np.array([[1],[2],[3],[4]]) @ np.array([5])

array([ 5, 10, 15, 20])

In [ ]:
np.dot(a, 5)

array([ 5, 10, 15, 20])

# Broadcasting

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

In [ ]:
array_2d + scalar

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d

In [ ]:
print(f"{array_2d} + {array_1d} =")
print("---"* 10)
print(result)

[[1 2 3]
 [4 5 6]] + [10 20 30] =
------------------------------
[[11 22 33]
 [14 25 36]]


In [ ]:
# Column matrix (3x1) and row matrix (1x3)
col_matrix = np.array([[1], [2], [3]])
row_matrix = np.array([[10, 20, 30]])

# Broadcasting works
result = col_matrix + row_matrix

print(f"{col_matrix} + {row_matrix} =")
print("---"* 10)
print(result)

[[1]
 [2]
 [3]] + [[10 20 30]] =
------------------------------
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2], [3, 4]])

result = array1 + array2
result

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

In [ ]:
print(array1.shape)
print(array2.shape)

(2, 3)
(2, 1)


In [ ]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20]])

In [ ]:
print(array1.shape)
print(array2.shape)
array1 + array2

(1, 3)
(2, 1)


array([[11, 12, 13],
       [21, 22, 23]])

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])
print(array1.shape)
print(array2.shape)
result = array1 + array2
result

(2, 3)
(1, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [ ]:
np.sum([1,2,3])

np.int64(6)

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([10, 20, 30])
print(array1.shape)
print(array2.shape)
result = array1 + array2
result

(2, 3)
(3,)


array([[11, 22, 33],
       [14, 25, 36]])