<a href="https://colab.research.google.com/github/ANILNbc2/ScalerAIMLCourse/blob/main/Module2Day02Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello AIML Batch July 2025")

Hello AIML Batch July 2025


In [ ]:
 students=[1,2,3,4,5]
 print(type(students))

<class 'list'>


#Some basic numpy functions.


We use numpy.array to create a numpy array. Numpy Arrays are homogenious and will type cast all elements to the same type.

```
So a = np.array(['1.2', 2.4 ])
will cause the array to become : ['1.2', '2.4']
```
To display the type of element, we can use type(object). This will tell us if the object is a numpy array. Its a python function.<br>
```
So print(type(a)) = \<class 'numpy.ndarray'\>
```
To display the type of the components of a numpy array, we use dtype.
```
So print(a.dytpe) = string.
```
To change the type of data (ie from String to float for example) we can use "astype(\<Target type\>). eg to convert array 'a' from String to float, we do

```
a = a.astype(float).
```
This will convert the type from String to float and save it back into the same array a.

In [ ]:
import numpy as np
#a = np.array(['string', 'str'])
a = np.array(['1.2'])
print(a.dtype)
print(type(a))
a= a.astype(float)
print(a.dtype)

<U3
<class 'numpy.ndarray'>
float64


#Indexing

In [ ]:
votes = np.array([775, 787, 918, 88, 166, 286, 2556, 324, 504, 402])
print(votes)
type(votes)
#To print the 4th element
print(votes[3])

[ 775  787  918   99  166  286 2556  324  504  402]
99


[1 2 3 4 5 6 7]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7])]


#Slicing


Slicing is the idea of how to get a continuous chunk of elements.
Negative indexing is available in python.
<br>For negative indexing, the indexes start from -1 and not 0. The last element is at -1 index. Count accordingly.

In [ ]:
print(votes)
#Indexing :
votes[3]
#Slicing
print(votes[1:4])
print(votes[len(votes)-1])
print(votes[-1])
print(votes[-5])

[ 775  787  918   99  166  286 2556  324  504  402]
[787 918  99]
402
402
286


#Covering negative Indexing slicing

```
For votes[:-2]
```
When the starting index is not mentioned, its assumed as starting from 0.
In this case, we are going upto -2, ie the second to last element.<br> As is the case with slicing, the last printed element is one less that the final index.

```
For votes[-3:]
```
The starting index is taken as the starting point and the final index is assumed as size of array.<br>So we get all elements from the starting index provided till the end of the array.




In [ ]:
print(votes)
print(votes[:-2])
print(votes[-3:])

[ 775  787  918   99  166  286 2556  324  504  402]
[ 775  787  918   99  166  286 2556  324]
[324 504 402]


#Fancy Indexing(Masking)

Masking is the concept in Numpy which nudges us towards filtering.

In numpy, when we do
```
print(votes *5)
[ 3875  3935  4590   495   830  1430 12780  1620  2520  2010]
```
we will multiple all the numbers in votes by 5.<br>
When we do an action like :

```
print(votes<100)
[False False False  True False False False False False False]
```
We will create a boolean array where each element indicates whether the corresponding value in the votes array is greater than 100.
<br>
We can also pass a boolean array as input to votes and get a filtered output.
For example, if we wanted to print only the even numbers :

```
print(votes )
print(votes[False True False  True False True False True False True]
[ 775  787  918   99  166  286 2556  324  504  402]
[787  99 286 324 402]
```
Only the true elements are printed. <br>
Another filter operation :
```
print(votes[votes<400])
[ 99 166 286 324]
```


In [ ]:
print(votes)
print(votes<100)
print(votes)
print(votes[[False, True, False, True, False, True, False, True, False, True]])
print(votes[votes<400])

[ 775  787  918   99  166  286 2556  324  504  402]
[False False False  True False False False False False False]
[ 775  787  918   99  166  286 2556  324  504  402]
[787  99 286 324 402]
[ 99 166 286 324]


#Column stacking

\<arrayName\>.shape gives the shape of the array.<br>
In case of a 1D array, it gives the output as (\<number of columns\>,)<br><br>

```
costs = np.array([ 77,78,91,9,16,28,255,32,50,40])
print(votes.shape)
print(costs.shape)
print("number of dimentions", votes.ndim)

(10,)
(10,)
number of dimentions 1
```


In case of multi dimention array, it goes for outermost to innermost. <br> So for a 2D array, the output is (\<Number of rows\>, \<Number of columns\>)<br><br>

ndim = number of dimentions. Gives us the number of dimentions the array has.<br>

np.column_stack(arr1, arr2) will first make the input array as vertical and then stack each of the mentioned arrays as the next column for the resultant array. <br><br>
So if the i/p arrays are [a1, a2, a3], [b1, b2, b3] and [c1, c2,c3], and we do
np.column_stack(a,b,c) the result will be <br>
[[a1, b1, c1]
 [a2, b2, c2]
 [a3, b3, c3]]


```
resturant_data =  np.column_stack((votes, costs))
print(resturant_data)
print("number of dimentions", resturant_data.ndim)
print("shape of resturant data", resturant_data.shape)

[[ 775   77]
 [ 787   78]
 [ 918   91]
 [  99    9]
 [ 166   16]
 [ 286   28]
 [2556  255]
 [ 324   32]
 [ 504   50]
 [ 402   40]]
number of dimentions 2
shape of resturant data (10, 2)
```





<br> np.row_stack has been depricated. Instead we have np.vstack(\<list of arrays\>)
The result is the arrays stacked vertically as expected. <br><br>

Arrays being stacked must of the same size or there will be error.


```
resturant_data =  np.vstack((votes, costs))
print(resturant_data)
print("number of dimentions", resturant_data.ndim)
print("shape of resturant data", resturant_data.shape)


[[ 775  787  918   99  166  286 2556  324  504  402]
 [  77   78   91    9   16   28  255   32   50   40]]
number of dimentions 2
shape of resturant data (2, 10)
```

In [ ]:
costs = np.array([ 77,78,91,9,16,28,255,32,50,40])
print(votes.shape)
print(costs.shape)
print("number of dimentions", votes.ndim)
resturant_data =  np.vstack((votes, costs))
print(resturant_data)
print("number of dimentions", resturant_data.ndim)
print("shape of resturant data", resturant_data.shape)
resturant_data =  np.column_stack((votes, costs))
print(resturant_data)
print("number of dimentions", resturant_data.ndim)
print("shape of resturant data", resturant_data.shape)


(10,)
(10,)
number of dimentions 1
[[ 775  787  918   99  166  286 2556  324  504  402]
 [  77   78   91    9   16   28  255   32   50   40]]
number of dimentions 2
shape of resturant data (2, 10)
[[ 775   77]
 [ 787   78]
 [ 918   91]
 [  99    9]
 [ 166   16]
 [ 286   28]
 [2556  255]
 [ 324   32]
 [ 504   50]
 [ 402   40]]
number of dimentions 2
shape of resturant data (10, 2)


#Reshaping a 2D array.

When we are dealing with 2D arrays, there are some simple techniques to reshare an array. There is a builtin function called reshape. The requirement is that when we use reshape, we should accomodate for all the values in the array. <br>
So, if the resturant data has 10 rows and 2 columns, then we have total of 20 elements. When we reshape, the total size of resultant array should also be the same. <br>


```
print(resturant_data)
resturant_data.reshape(4,5)

[[ 775   77]
 [ 787   78]
 [ 918   91]
 [  99    9]
 [ 166   16]
 [ 286   28]
 [2556  255]
 [ 324   32]
 [ 504   50]
 [ 402   40]]


array([[ 775,   77,  787,   78,  918],
       [  91,   99,    9,  166,   16],
       [ 286,   28, 2556,  255,  324],
       [  32,  504,   50,  402,   40]])
```

If we dont want to calculate, or not sure how many total elements are there, then we can just mention the number of rows or columns and substitute the other dimention by -1 as below : <br>

```
print(resturant_data.reshape(5,-1))


[[ 775   77  787   78]
 [ 918   91   99    9]
 [ 166   16  286   28]
 [2556  255  324   32]
 [ 504   50  402   40]]

```


```
print(resturant_data.reshape(-1,5))

[[ 775   77  787   78  918]
 [  91   99    9  166   16]
 [ 286   28 2556  255  324]
 [  32  504   50  402   40]]


```



In [ ]:
print(resturant_data)
print(resturant_data.reshape(4,5))
print(resturant_data.reshape(5,-1))
print(resturant_data.reshape(-1,5))

[[ 775   77]
 [ 787   78]
 [ 918   91]
 [  99    9]
 [ 166   16]
 [ 286   28]
 [2556  255]
 [ 324   32]
 [ 504   50]
 [ 402   40]]
[[ 775   77  787   78  918]
 [  91   99    9  166   16]
 [ 286   28 2556  255  324]
 [  32  504   50  402   40]]
[[ 775   77  787   78]
 [ 918   91   99    9]
 [ 166   16  286   28]
 [2556  255  324   32]
 [ 504   50  402   40]]
[[ 775   77  787   78  918]
 [  91   99    9  166   16]
 [ 286   28 2556  255  324]
 [  32  504   50  402   40]]
