<a href="https://colab.research.google.com/github/ANILNbc2/ScalerAIMLCourse/blob/main/Module02Day03Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
resturant_data = np.array([[775,  787,  918,   99,  166,  286, 2556,  324,  504,  402],
                           [ 77, 78, 91, 9, 16, 28, 255, 32, 50, 40]])
print(resturant_data)
resturant_data = np.column_stack(resturant_data)
print(resturant_data)

[[ 775  787  918   99  166  286 2556  324  504  402]
 [  77   78   91    9   16   28  255   32   50   40]]
[[ 775   77]
 [ 787   78]
 [ 918   91]
 [  99    9]
 [ 166   16]
 [ 286   28]
 [2556  255]
 [ 324   32]
 [ 504   50]
 [ 402   40]]


In [4]:
print(resturant_data[:][0:1])

[[775  77]]


In [11]:
resturant_data = np.array([[775,  787,  918,   99,  166,  286, 2556,  324,  504,  402],
                           [ 77, 78, 91, 9, 16, 28, 255, 32, 50, 40]])

resturant_data = np.column_stack((np.column_stack(resturant_data), np.column_stack(resturant_data + 100), np.column_stack(resturant_data + 200)))
resturant_data = np.vstack((resturant_data + resturant_data, resturant_data + 200))
print(resturant_data)

[[1550  154 1750  354 1950  554]
 [1574  156 1774  356 1974  556]
 [1836  182 2036  382 2236  582]
 [ 198   18  398  218  598  418]
 [ 332   32  532  232  732  432]
 [ 572   56  772  256  972  456]
 [5112  510 5312  710 5512  910]
 [ 648   64  848  264 1048  464]
 [1008  100 1208  300 1408  500]
 [ 804   80 1004  280 1204  480]
 [ 975  277 1075  377 1175  477]
 [ 987  278 1087  378 1187  478]
 [1118  291 1218  391 1318  491]
 [ 299  209  399  309  499  409]
 [ 366  216  466  316  566  416]
 [ 486  228  586  328  686  428]
 [2756  455 2856  555 2956  655]
 [ 524  232  624  332  724  432]
 [ 704  250  804  350  904  450]
 [ 602  240  702  340  802  440]]


#2D Slicing

When slicing a 2D array, we need to provide both row and column to slice on. <br> The way to do this is : \<Array name\>[row start:row end, col start:col end]

In [6]:
print(resturant_data.shape)
print(resturant_data.ndim)
print("\nJust row slice : resturant_data[0:5,:]")
print(resturant_data[0:5,:])
print("\nWith column slice : resturant_data[0:5,-3:]")
print(resturant_data[0:5,-3:])

(20, 6)
2

Just row slice : resturant_data[0:5,:]
[[1550  154 1750  354 1950  554]
 [1574  156 1774  356 1974  556]
 [1836  182 2036  382 2236  582]
 [ 198   18  398  218  598  418]
 [ 332   32  532  232  732  432]]

With column slice : resturant_data[0:5,-3:]
[[ 354 1950  554]
 [ 356 1974  556]
 [ 382 2236  582]
 [ 218  598  418]
 [ 232  732  432]]


In [12]:
# Get 4th to 10th row of 2nd column
#print(resturant_data , "\n\n\n")
#print(resturant_data[4:9, :])
print(resturant_data[3:10], "\n\n\n")

twoDarray = resturant_data[3:10,1:2]
oneDArray = resturant_data[3:10,1]
print(twoDarray,"\ntwoDarray.shape : ", twoDarray.shape, "\ntwoDarray.size : ", twoDarray.size,"\ntwoDarray.ndim : ", twoDarray.ndim,"\n\n\n")
print(oneDArray,"\noneDArray.shape ; ", oneDArray.shape, "\noneDArray.size ; ", oneDArray.size, "\noneDArray.ndim : ", oneDArray.ndim)


[[ 198   18  398  218  598  418]
 [ 332   32  532  232  732  432]
 [ 572   56  772  256  972  456]
 [5112  510 5312  710 5512  910]
 [ 648   64  848  264 1048  464]
 [1008  100 1208  300 1408  500]
 [ 804   80 1004  280 1204  480]] 



[[ 18]
 [ 32]
 [ 56]
 [510]
 [ 64]
 [100]
 [ 80]] 
twoDarray.shape :  (7, 1) 
twoDarray.size :  7 
twoDarray.ndim :  2 



[ 18  32  56 510  64 100  80] 
oneDArray.shape ;  (7,) 
oneDArray.size ;  7 
oneDArray.ndim :  1


#Aggregate functions

We try to summrize the data in a meaningful manner by using Aggregation.
Certain functions are well defined to perform summerization. eg np.sum(\<Array\>) to get the sum of array. for example, if we want to sum all the values in the 3rd column of the resturant_data. np.sum(resturant_data[:,2])
<br><br>
We could have just used sum(resturant_data[:,2] but then we will be using the baseline python function which does not use vectroization and hence will be slow.

In [20]:
print(np.sum(resturant_data[:,2]))
# we can also do :
resturant_data[:,2].sum()
#The <np array>.sum() is a function which runs on an instance of a numpy array and the resonse will be a numpy sum function.
np.sum(resturant_data[:,2])



25451


np.int64(25451)

In [24]:
#how to get avarage cost of 10 resturants. Cost is the 2nd column in the resturant_data
print(resturant_data[:10,1].mean())
#This is the same as : resturant_data[:10,1].sum()/10
print (resturant_data[:10,1].sum()/10)

135.2
135.2


In [27]:
#min and max vote. Vote is the 1st column in the array.
print(resturant_data[:,0].min())
print(resturant_data[:,0].max())




198
5112
