<a href="https://colab.research.google.com/github/ANILNbc2/ScalerAIMLCourse/blob/main/Module02Day03Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
resturant_data = np.array([[775,  787,  918,   99,  166,  286, 2556,  324,  504,  402],
                           [ 77, 78, 91, 9, 16, 28, 255, 32, 50, 40]])
print(resturant_data)
resturant_data = np.column_stack(resturant_data)
print(resturant_data)

[[ 775  787  918   99  166  286 2556  324  504  402]
 [  77   78   91    9   16   28  255   32   50   40]]
[[ 775   77]
 [ 787   78]
 [ 918   91]
 [  99    9]
 [ 166   16]
 [ 286   28]
 [2556  255]
 [ 324   32]
 [ 504   50]
 [ 402   40]]


In [3]:
print(resturant_data[:][0:1])

[[775  77]]


In [4]:
resturant_data = np.array([[775,  787,  918,   99,  166,  286, 2556,  324,  504,  402],
                           [ 77, 78, 91, 9, 16, 28, 255, 32, 50, 40]])

resturant_data = np.column_stack((np.column_stack(resturant_data), np.column_stack(resturant_data + 100), np.column_stack(resturant_data + 200)))
resturant_data = np.vstack((resturant_data + resturant_data, resturant_data + 200))
print(resturant_data)

[[1550  154 1750  354 1950  554]
 [1574  156 1774  356 1974  556]
 [1836  182 2036  382 2236  582]
 [ 198   18  398  218  598  418]
 [ 332   32  532  232  732  432]
 [ 572   56  772  256  972  456]
 [5112  510 5312  710 5512  910]
 [ 648   64  848  264 1048  464]
 [1008  100 1208  300 1408  500]
 [ 804   80 1004  280 1204  480]
 [ 975  277 1075  377 1175  477]
 [ 987  278 1087  378 1187  478]
 [1118  291 1218  391 1318  491]
 [ 299  209  399  309  499  409]
 [ 366  216  466  316  566  416]
 [ 486  228  586  328  686  428]
 [2756  455 2856  555 2956  655]
 [ 524  232  624  332  724  432]
 [ 704  250  804  350  904  450]
 [ 602  240  702  340  802  440]]


#2D Slicing

When slicing a 2D array, we need to provide both row and column to slice on. <br> The way to do this is : \<Array name\>[row start:row end, col start:col end]

In [5]:
print(resturant_data.shape)
print(resturant_data.ndim)
print("\nJust row slice : resturant_data[0:5,:]")
print(resturant_data[0:5,:])
print("\nWith column slice : resturant_data[0:5,-3:]")
print(resturant_data[0:5,-3:])

(20, 6)
2

Just row slice : resturant_data[0:5,:]
[[1550  154 1750  354 1950  554]
 [1574  156 1774  356 1974  556]
 [1836  182 2036  382 2236  582]
 [ 198   18  398  218  598  418]
 [ 332   32  532  232  732  432]]

With column slice : resturant_data[0:5,-3:]
[[ 354 1950  554]
 [ 356 1974  556]
 [ 382 2236  582]
 [ 218  598  418]
 [ 232  732  432]]


In [6]:
# Get 4th to 10th row of 2nd column
#print(resturant_data , "\n\n\n")
#print(resturant_data[4:9, :])
print(resturant_data[3:10], "\n\n\n")

twoDarray = resturant_data[3:10,1:2]
oneDArray = resturant_data[3:10,1]
print(twoDarray,"\ntwoDarray.shape : ", twoDarray.shape, "\ntwoDarray.size : ", twoDarray.size,"\ntwoDarray.ndim : ", twoDarray.ndim,"\n\n\n")
print(oneDArray,"\noneDArray.shape ; ", oneDArray.shape, "\noneDArray.size ; ", oneDArray.size, "\noneDArray.ndim : ", oneDArray.ndim)


[[ 198   18  398  218  598  418]
 [ 332   32  532  232  732  432]
 [ 572   56  772  256  972  456]
 [5112  510 5312  710 5512  910]
 [ 648   64  848  264 1048  464]
 [1008  100 1208  300 1408  500]
 [ 804   80 1004  280 1204  480]] 



[[ 18]
 [ 32]
 [ 56]
 [510]
 [ 64]
 [100]
 [ 80]] 
twoDarray.shape :  (7, 1) 
twoDarray.size :  7 
twoDarray.ndim :  2 



[ 18  32  56 510  64 100  80] 
oneDArray.shape ;  (7,) 
oneDArray.size ;  7 
oneDArray.ndim :  1


#Aggregate functions

We try to summrize the data in a meaningful manner by using Aggregation.
Certain functions are well defined to perform summerization. eg np.sum(\<Array\>) to get the sum of array. for example, if we want to sum all the values in the 3rd column of the resturant_data. np.sum(resturant_data[:,2])
<br><br>
We could have just used sum(resturant_data[:,2] but then we will be using the baseline python function which does not use vectroization and hence will be slow.

In [7]:
print(np.sum(resturant_data[:,2]))
# we can also do :
resturant_data[:,2].sum()
#The <np array>.sum() is a function which runs on an instance of a numpy array and the resonse will be a numpy sum function.
np.sum(resturant_data[:,2])



25451


np.int64(25451)

In [8]:
#how to get avarage cost of 10 resturants. Cost is the 2nd column in the resturant_data
print(resturant_data[:10,1].mean())
#This is the same as : resturant_data[:10,1].sum()/10
print (resturant_data[:10,1].sum()/10)

135.2
135.2


In [9]:
#min and max vote. Vote is the 1st column in the array.
print(resturant_data[:,0].min())
print(resturant_data[:,0].max())




198
5112


In [10]:
#Reshaping resturant for matching lecture, the table should have 2 columns, unknown number or rows.
resturant_data = resturant_data.reshape(-1,2)
print(resturant_data)
print(resturant_data.shape)

[[1550  154]
 [1750  354]
 [1950  554]
 [1574  156]
 [1774  356]
 [1974  556]
 [1836  182]
 [2036  382]
 [2236  582]
 [ 198   18]
 [ 398  218]
 [ 598  418]
 [ 332   32]
 [ 532  232]
 [ 732  432]
 [ 572   56]
 [ 772  256]
 [ 972  456]
 [5112  510]
 [5312  710]
 [5512  910]
 [ 648   64]
 [ 848  264]
 [1048  464]
 [1008  100]
 [1208  300]
 [1408  500]
 [ 804   80]
 [1004  280]
 [1204  480]
 [ 975  277]
 [1075  377]
 [1175  477]
 [ 987  278]
 [1087  378]
 [1187  478]
 [1118  291]
 [1218  391]
 [1318  491]
 [ 299  209]
 [ 399  309]
 [ 499  409]
 [ 366  216]
 [ 466  316]
 [ 566  416]
 [ 486  228]
 [ 586  328]
 [ 686  428]
 [2756  455]
 [2856  555]
 [2956  655]
 [ 524  232]
 [ 624  332]
 [ 724  432]
 [ 704  250]
 [ 804  350]
 [ 904  450]
 [ 602  240]
 [ 702  340]
 [ 802  440]]
(60, 2)


#Using Axis in Aggrigation

Axis gives the function a direction to perform the action on. <br>
If Axis param value is 0, then we go vertically and if 1, then horizontally.

ie. axis=0, then vertically. axis=1 then horizontally.


```
print(data)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

print(np.sum(data, axis=0))
[12 15 18 21]

here
12 = 0+4+8 (sum of all values in first col)
15 = 1+5+9 (sum of all values in second col)
18 = 2+6+10 (sum of all values in third col)
21 = 3+7+11 (sum of all values in fourth col)

Essentially, we can think of axis 0 as follows :
if axis=0, and we are asking to perform sum, then the message is :
1. Select each column, in this case, we have 4 columns.
2. Now perfrom the action (in this case, sum) on every column.
3. ie Select col 0,(returns 1 D array of all values in col 0 for every row). perform sum, add to a restunant array at col 0, Perfrom same action for all remaining columns.  
4. This turns into perfrom the said action vertically...  

print(np.sum(data, axis=1))<br>
[ 6 22 38]
6 = 0+1+2+3 (sum of all values in first row)
22 = 4+5+6+7 (sum of all values in second row)
38 = 8+9+10+11 (sum of all values in third row)

Essentially, we can think of axis 1 as follows :
if axis=1, and we are asking to perform sum, then the message is :
1. Select each row, in this case, we have 3 rows.
2. Now perfrom the action (in this case, sum) on every row.
3. ie Select row 0,(returns 1 D array of all values in  row 0).
Perform sum, add to a restunant array at col 0, Perfrom same action for all remaining rows.  
4. This turns into perfrom the said action horizontally...  
```





In [11]:
data = np.arange(12).reshape(3,4)
print(data)
print(np.sum(data, axis=0))
print(np.sum(data, axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


#Logical Operators

Numpy logical operators :
1. Where : Similar usage as SQL
eg : np.where(costs > 200)

np.where() always returns a tuple of arrays because it's designed for multi-dimensional indexing in NumPy.
General Behavior of np.where(condition)<br>
For a 2D array, the condition check produces a 2D boolean array.

np.where() then returns one array per dimension:

First array → all the matching row indices
Second array → all the matching column indices

\#For clarity, I am reducing the number of rows and columns printed below<br>
output :

(array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16...]), <br>
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...]))

For example, the value at costs[1][0] is > 200. where 1 is the first entry from the first array and 0 is the first entry in the second array above.

2.

In [12]:
#0th column is votes, 1st is costs.
costs=resturant_data[:,1:]
votes = resturant_data[:,0:1]
print(np.where(costs>200))

(array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 22, 23,
       25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0]))


In [13]:
print(np.where(costs > 200))

(array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 22, 23,
       25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0]))


#What happes when we use where clause in a 1D array?
In case if we exectue the Where clause on a 1D array
If we concert 2D array to 1D array, then we get a 1D array as outout.

In [17]:
costs1D= costs.reshape(1,-1)[0]
print(np.where(costs1D>200))

(array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 22, 23,
       25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),)


#With & and ||

Where clause with & : **costs1D[np.where((costs1D>200)&(costs1D<400))]** <br><br>
Each of the conditions need to be in its own bracket :  **np.where((clause1)&(clause2))**

We can use **and** only in baseline python. In numpy, we can use "and" on scaler values in numpy (eg true and false) but not with arrays and other structures where we have more than 1 value present. ie it does not work in a vectorized env, which is what numpy gives us.

In [24]:

#This will work :
print(((2==2)and(3==3)))

#This will throw an error
#print(costs1D[np.where((costs1D>200) and (costs1D<400))])
#but this wont :
print(costs1D[np.where((costs1D>200)&(costs1D<400))])

True
[354 356 382 218 232 256 264 300 280 277 377 278 378 291 391 209 309 216
 316 228 328 232 332 250 350 240 340]


#Any and All


In [27]:
# Are there any resturants with costs > 800
np.any(costs>800)
# This is true, which means there is at least 1 resturant with cost > 800

np.True_

In [26]:
# Are the costs of all the resturants > 800
np.all(costs>800)
# This is false, which means there is at least 1 resturant with cost < 800

np.False_

In [54]:
resturant_data_10x = resturant_data.reshape(10,-1)
print(resturant_data_10x,"\n\n")
print(costs1D)

[[1550  154 1750  354 1950  554 1574  156 1774  356 1974  556]
 [1836  182 2036  382 2236  582  198   18  398  218  598  418]
 [ 332   32  532  232  732  432  572   56  772  256  972  456]
 [5112  510 5312  710 5512  910  648   64  848  264 1048  464]
 [1008  100 1208  300 1408  500  804   80 1004  280 1204  480]
 [ 975  277 1075  377 1175  477  987  278 1087  378 1187  478]
 [1118  291 1218  391 1318  491  299  209  399  309  499  409]
 [ 366  216  466  316  566  416  486  228  586  328  686  428]
 [2756  455 2856  555 2956  655  524  232  624  332  724  432]
 [ 704  250  804  350  904  450  602  240  702  340  802  440]] 


[154 354 554 156 356 556 182 382 582  18 218 418  32 232 432  56 256 456
 510 710 910  64 264 464 100 300 500  80 280 480 277 377 477 278 378 478
 291 391 491 209 309 409 216 316 416 228 328 428 455 555 655 232 332 432
 250 350 450 240 340 440]


#Sort and argsort

sort will sort the 1D array or sort a 2D array by last axis value(axis=-1) and give output.<br>
For a 1D array, the axis value has no meaning. For a 2D array it will take axis=1 and for 3D it will take axis=2<br>
Argsort will sort the 1D array or sort a 2D array by by last axis value(axis=-1) and give the output as the original index of the value at the sorted position.<br><br>
We can also pass **axis** to sort. With this, the sort algo will perform sort by row or by column. If we pass 1, it will sort horizontally, ie rowwise. and if we pass 0, it will sort per column.

print(np.sort(resturant_data_10x,0),"\n\n")
print(np.argsort(resturant_data_10x,0),"\n\n")



In [52]:

print(np.sort(costs1D),"\n\n")
print(np.argsort(costs1D),"\n\n")

print(np.sort(resturant_data_10x,0),"\n\n")
print(np.argsort(resturant_data_10x,0),"\n\n")


[ 18  32  56  64  80 100 154 156 182 209 216 218 228 232 232 240 250 256
 264 277 278 280 291 300 309 316 328 332 340 350 354 356 377 378 382 391
 409 416 418 428 432 432 440 450 455 456 464 477 478 480 491 500 510 554
 555 556 582 655 710 910] 


[ 9 12 15 21 27 24  0  3  6 39 42 10 45 51 13 57 54 16 22 30 33 28 36 25
 40 43 46 52 58 55  1  4 31 34  7 37 41 44 11 47 14 53 59 56 48 17 23 32
 35 29 38 26 18  2 49  5  8 50 19 20] 


[[ 332   32  466  232  566  416  198   18  398  218  499  409]
 [ 366  100  532  300  732  432  299   56  399  256  598  418]
 [ 704  154  804  316  904  450  486   64  586  264  686  428]
 [ 975  182 1075  350 1175  477  524   80  624  280  724  432]
 [1008  216 1208  354 1318  491  572  156  702  309  802  440]
 [1118  250 1218  377 1408  500  602  209  772  328  972  456]
 [1550  277 1750  382 1950  554  648  228  848  332 1048  464]
 [1836  291 2036  391 2236  582  804  232 1004  340 1187  478]
 [2756  455 2856  555 2956  655  987  240 1087  356 1204  480

#Marix Operations

Usually  numpy performs elementwise operation.<br>
So : if Arr2D-a of size (x,y) and Arr2D-b of size (x,y) <br>
then<br>
Arr2D-a * Arr2D-b = Arr2D-ab of size (x,y) ,where<br> Arr2D-ab(xi,yi) = Arr2D-a(xi,yi) * Arr2D-b(xi,yi)
<br><br>
ie an elementwise action takes place.<br>
<br>
#Actual Matrix Multiplication
For real Matrix multiplication, we need to have 2 arrays A,B such that<br>
A(MxN) and B(NxP) ie the number of cols on the first matrix should match the number of rows on second matrix. The resultant will be C(MxP)<br><br>
A(MxN) * B(NxP) = C(MxP)
<br>
There are 2 functions in numpy which will help us accomplish this : <br>
np.dot(A,B) and np.matmul(A,B)
<br><br>
As '*' has already taken up for multiplication, we have another symbol '@' which has been assigned the dot product symbol.



```
A = np.arange(1,13).reshape(3,4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

B = np.arange(13,25).reshape(4,3)
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

C = np.dot(A,B)
D = np.matmul(A,B)
E =  A@B
print(C)
[[190 200 210]
 [470 496 522]
 [750 792 834]]

print(D)
[[190 200 210]
 [470 496 522]
 [750 792 834]]

print(E)
[[190 200 210]
 [470 496 522]
 [750 792 834]]

```



In [66]:
A = np.arange(1,13).reshape(3,4)
print(A,"\n\n")
B = np.arange(13,25).reshape(4,3)
print(B,"\n\n")
C = np.dot(A,B)
D = np.matmul(A,B)
E = A @ B

print(C,"\n\n")

print(D,"\n\n")

print(E,"\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]] 


[[190 200 210]
 [470 496 522]
 [750 792 834]] 


[[190 200 210]
 [470 496 522]
 [750 792 834]] 


[[190 200 210]
 [470 496 522]
 [750 792 834]] 




In [69]:
np.dot(A,5)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

#Broadcasting

In NumPy, broadcasting is the set of rules it uses to perform operations on arrays of different shapes without making unnecessary copies of data.

It lets NumPy automatically expand smaller arrays to match the shape of larger ones so you can write cleaner, vectorized code.

1️⃣ The Basic Idea
If two arrays don’t have the same shape:

NumPy tries to “stretch” the smaller one along dimensions where they differ.

This stretching is virtual — it doesn’t copy data, just reuses it in memory.

2️⃣ The Broadcasting Rules
When comparing shapes of two arrays:

Compare dimensions starting from the rightmost.

For each dimension:

If the dimensions are equal → ✅ compatible

If one of them is 1 → ✅ compatible (the size 1 is stretched to match)

Otherwise → ❌ incompatible (broadcasting fails)

Example 1 — Scalar & Array
python
Copy
import numpy as np

a = np.array([1, 2, 3])  # shape: (3,)
b = 2                    # scalar

print(a + b)  # Broadcasting scalar to shape (3,)
Output:

csharp
Copy
[3 4 5]
Here, 2 is virtually replicated into [2, 2, 2].

Example 2 — 1D and 2D Array
python
Copy
a = np.array([[1],
              [2],
              [3]])  # shape (3,1)
b = np.array([10, 20, 30])  # shape (3,)

# Shapes from right: (1) vs (3) → stretch column of a
# Leftmost dimension: (3) vs (3) → match
print(a + b)
Output:

lua
Copy
[[11 21 31]
 [12 22 32]
 [13 23 33]]
Example 3 — Incompatible Shapes
python
Copy
a = np.ones((3, 2))
b = np.ones((3, 3))

# Last dimension: 2 vs 3 → ❌ not equal and neither is 1
print(a + b)  # ValueError
3️⃣ Why Broadcasting Matters
Avoids loops → faster execution

Saves memory → no need to explicitly expand arrays

Enables cleaner, more Pythonic code

In your np.where(costs > 200) example:
If costs was (60, 1) and you compared with 200 (scalar), NumPy broadcasted 200 to shape (60, 1) before doing the comparison — without actually creating a (60, 1) array of 200s.

In [84]:
array_2d = np.arange(1,7).reshape(2,-1)
array_1d = np.arange(10,31,10)
scaler = 10
print(array_2d,"\n")
print(array_2d+scaler,"\n")
print(array_1d,"\n")
print((array_2d + array_1d),"\n")

[[1 2 3]
 [4 5 6]] 

[[11 12 13]
 [14 15 16]] 

[10 20 30] 

[[11 22 33]
 [14 25 36]] 

