<a href="https://colab.research.google.com/github/ANILNbc2/ScalerAIMLCourse/blob/main/Module02Day04Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Splitting an array.

In [2]:
import numpy as np
array_1D = np.arange(1,8)
print(array_1D)
#not_working_split = np.split(array_1D, 3)
#This doesnt work, throws error : ValueError: array split does not result in an equal division
split_1d = np.split(array_1D,7)

#This generates a list of arrays :  [array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7])]
print(split_1d)

# Splitting in 2D array :
array_2d = np.arange(1,9).reshape(2,-1)
print(array_2d)
split_2d = np.split(array_2d,2, 0)
print(split_2d)

split_2d = np.split(array_2d,2, 1)
print(split_2d)


[1 2 3 4 5 6 7]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7])]
[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [3]:
# Splitting in 2D array :
array_2d = np.arange(1,9).reshape(2,-1)
print(array_2d)
split_2d = np.hsplit(array_2d,2)
print("Horizontal Split : \n")
for arr in split_2d :
  print(arr,"\n")

print("Vertical Split : \n")
split_2d = np.vsplit(array_2d,2)
for arr in split_2d :
  print(arr,"\n")




[[1 2 3 4]
 [5 6 7 8]]
Horizontal Split : 

[[1 2]
 [5 6]] 

[[3 4]
 [7 8]] 

Vertical Split : 

[[1 2 3 4]] 

[[5 6 7 8]] 



#Concatination

In [4]:
array_2d = np.arange(1,9).reshape(2,-1)
split_2dh = np.hsplit(array_2d,2)
split_2dv = np.vsplit(array_2d,2)

print(split_2dh[0],"\n\n",split_2dh[1],"\n\n")
concat_cols = np.concatenate([split_2dh[0], split_2dh[1]],0)
print(concat_cols,"\n\n\n")
#concat_cols = np.concatenate([split_2dh[0], concat_cols],0)
#print(concat_cols)
concat_cols = np.concatenate([split_2dh[0], split_2dh[1]],1)
print(concat_cols)

#If the number of cells in the direction of merge dont match, then the
#concatination will fail. The below code wont work.
#concat_cols = np.concatenate([split_2dh[0], concat_cols],0)
#print(concat_cols)

[[1 2]
 [5 6]] 

 [[3 4]
 [7 8]] 


[[1 2]
 [5 6]
 [3 4]
 [7 8]] 



[[1 2 3 4]
 [5 6 7 8]]


#np.tile



Whenever there is an incompatability that broadcast is unable to resolve, we can use tile to make things right.
For example in case of this :


```
array1 = np.array([[1,2,3]])
array2 = np.array([[10],[11],[12]])
#we cannot do a somple stack as the array shapes are different, but with tile
#we can do :

array3 = np.tile(arra1

```



In [5]:
array1 = np.array([[1,2,3]])
array2 = np.array([[10],[11],[12]])
#we cannot do a somple stack as the array shapes are different, but with tile
#we can do :
#array3 = np.tile((array1,array2(3,1)))

#Instead we can do :
# Repeat array1 vertically 3 times
array1_tiled = np.tile(array1, (3, 1))  # shape becomes (3, 3)

#[[ 1  2  3]
# [ 1  2  3]
# [ 1  2  3]]

# Combine side-by-side
#array3 = np.hstack((array1_tiled, array2))
#print(array3)

#Here, by using tile, we are able to stack the array1 multiple times.
array1 = np.array([[1,2,3]])
array1_tiled = np.tile(array1, (2, 1))  # shape becomes (3, 3)
print(array1_tiled)

# For np.tile, we give as params, the number of times we want the array to be
# repeated along the rows and the number of times the cells should be repeated
# along the columns.
# So, for an array [1,2,3], if we give np.tile(array1, (3,2)) then we are saying
# in the final array, the values of the array = (1,2,3) should be repeated 3
# times rowwise and 2 time column wise.

# 3 times row wise :
 # [[1,2,3]
 #  [1,2,3]
 #  [1,2,3]]

 # and 2 times column wise
# [[1,2,3,1,2,3]
#  [1,2,3,1,2,3]
#  [1,2,3,1,2,3]]

# np.tile(array, reps)
# array → The input NumPy array.
# reps → Number of repetitions for each axis:
# If reps is a scalar → repeats along the first axis (for 1D arrays).
# If reps is a tuple → repeats along each axis.

[[1 2 3]
 [1 2 3]]


#Moving to Pandas.
#Why pandas?

 Labeled Data Support
NumPy arrays are purely positional — you reference data by index.

Pandas adds labels (row indices and column names) so you can reference data more naturally:

python
Copy
import numpy as np
import pandas as pd

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=['A', 'B'])

print(df['A'])  # Access by column name instead of position

2️⃣ Handling Heterogeneous Data
NumPy arrays must be homogeneous (all elements same type).

Pandas can store mixed types (int, float, string, datetime) in columns — perfect for real-world datasets.

3️⃣ Built-in Data Cleaning Tools
Pandas has built-in handling for:

Missing data (NaN) with .fillna(), .dropna()

Type conversion (.astype())

Index alignment when combining datasets

NumPy doesn’t have direct missing data handling — you need workarounds.

4️⃣ High-Level Operations
Pandas has groupby, pivot, merge, join, rolling windows — great for analytics.

NumPy focuses on low-level array math — you’d need to code grouping/aggregation manually.

5️⃣ Read/Write Support
Pandas can directly read/write from:

CSV, Excel, SQL, JSON, Parquet, etc.

df = pd.read_csv('data.csv')
NumPy can load text and binary files but has limited format support.

6️⃣ Easier Exploration
Pandas integrates nicely with Jupyter/interactive notebooks:

Pretty table display

.head() / .tail() for quick peeks

Descriptive statistics with .describe()

When to use which
Use Case	Better Tool
Pure numerical computation (linear algebra, ML input arrays)	NumPy
Tabular data, analytics, cleaning, joining	Pandas


Pandas a wrapper over Numpy

#How to run terminal command on notebook??

We start the command with a '!' mark. So everytime we want to execute the command on terminal such as wget or unzip, we will preface it with '!'

In [6]:
# Downloading and unziping the dataset
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv .

--2025-08-11 15:33:59--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 13.226.65.83, 13.226.65.51, 13.226.65.68, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|13.226.65.83|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M  35.0MB/s    in 2.0s    

2025-08-11 15:34:02 (35.0 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv      
mv: 'zomato_dataset.csv' and './zomato_dataset.csv' are the same file


In [7]:
import pandas as pd

df = pd.read_csv('/content/zomato_dataset.csv')
print(df)

                                                     url  \
0      https://www.zomato.com/bangalore/jalsa-banasha...   
1      https://www.zomato.com/bangalore/spice-elephan...   
2      https://www.zomato.com/SanchurroBangalore?cont...   
3      https://www.zomato.com/bangalore/addhuri-udupi...   
4      https://www.zomato.com/bangalore/grand-village...   
...                                                  ...   
23188  https://www.zomato.com/bangalore/izakaya-gastr...   
23189  https://www.zomato.com/bangalore/m-bar-bengalu...   
23190  https://www.zomato.com/bangalore/keys-cafe-key...   
23191  https://www.zomato.com/bangalore/bhagini-2-whi...   
23192  https://www.zomato.com/bangalore/chime-sherato...   

                                                 address  \
0      942, 21st Main Road, 2nd Stage, Banashankari, ...   
1      2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...   
2      1112, Next to KIMS Medical College, 17th Cross...   
3      1st Floor, Annakuteera, 3rd Stag

In [8]:
df

url  \
0      https://www.zomato.com/bangalore/jalsa-banasha...   
1      https://www.zomato.com/bangalore/spice-elephan...   
2      https://www.zomato.com/SanchurroBangalore?cont...   
3      https://www.zomato.com/bangalore/addhuri-udupi...   
4      https://www.zomato.com/bangalore/grand-village...   
...                                                  ...   
23188  https://www.zomato.com/bangalore/izakaya-gastr...   
23189  https://www.zomato.com/bangalore/m-bar-bengalu...   
23190  https://www.zomato.com/bangalore/keys-cafe-key...   
23191  https://www.zomato.com/bangalore/bhagini-2-whi...   
23192  https://www.zomato.com/bangalore/chime-sherato...   

                                                 address  \
0      942, 21st Main Road, 2nd Stage, Banashankari, ...   
1      2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...   
2      1112, Next to KIMS Medical College, 17th Cross...   
3      1st Floor, Annakuteera, 3rd Stage, Banashankar...   
4      10, 3rd Floor, Lakshmi Associates, Gandhi Baza...   
...                                                  ...   
23188  2nd Floor, Iona, Virginia Mall, Whitefield Mai...   
23189  Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...   
23190  Keys Hotel, 6, 1st Phase Industrial Area, Near...   
23191  139/C1, Next To GR Tech Park, Pattandur Agraha...   
23192  Sheraton Grand Bengaluru Whitefield Hotel & Co...   

                                                    name online_order  \
0                                                  Jalsa          Yes   
1                                         Spice Elephant          Yes   
2                                        San Churro Cafe          Yes   
3                                  Addhuri Udupi Bhojana           No   
4                                          Grand Village           No   
...                                                  ...          ...   
23188                                 Izakaya Gastro Pub          Yes   
23189        M Bar - Bengaluru Marriott Hotel Whitefield           No   
23190                             Keys Cafe - Keys Hotel           No   
23191                                            Bhagini           No   
23192  Chime - Sheraton Grand Bengaluru Whitefield Ho...           No   

      book_table    rate  votes                             phone  \
0            Yes   4.1/5    775    080 42297555\r\n+91 9743772233   
1             No   4.1/5    787                      080 41714161   
2             No   3.8/5    918                    +91 9663487993   
3             No   3.7/5     88                    +91 9620009302   
4             No   3.8/5    166  +91 8026612447\r\n+91 9901210005   
...          ...     ...    ...                               ...   
23188        Yes  3.8 /5    128    +91 7625087121\n+91 8050587483   
23189         No  3.9 /5     77                      080 49435000   
23190         No  2.8 /5    161      080 39451000\n+91 8884038484   
23191         No  2.5 /5     81                      080 65951222   
23192        Yes  4.3 /5    236                      080 49652769   

                         location            rest_type  \
0                    Banashankari        Casual Dining   
1                    Banashankari        Casual Dining   
2                    Banashankari  Cafe, Casual Dining   
3                    Banashankari          Quick Bites   
4                    Basavanagudi        Casual Dining   
...                           ...                  ...   
23188                  Whitefield   Bar, Casual Dining   
23189                  Whitefield     Fine Dining, Bar   
23190                  Whitefield   Casual Dining, Bar   
23191                  Whitefield   Casual Dining, Bar   
23192  ITPL Main Road, Whitefield                  Bar   

                                              dish_liked  \
0      Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1      Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2      Churros, Cannelloni, 

Dataframe is the primary datastruture used in pandas.
In pandas, the dataframe is equivalent of table in excel sheet.

Pandas is implemented on top of numpy

In [9]:
print(type(df))
print(type(df.values))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [10]:
 df.head()

url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...   
1  https://www.zomato.com/bangalore/spice-elephan...   
2  https://www.zomato.com/SanchurroBangalore?cont...   
3  https://www.zomato.com/bangalore/addhuri-udupi...   
4  https://www.zomato.com/bangalore/grand-village...   

                                             address                   name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...                  Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...         Spice Elephant   
2  1112, Next to KIMS Medical College, 17th Cross...        San Churro Cafe   
3  1st Floor, Annakuteera, 3rd Stage, Banashankar...  Addhuri Udupi Bhojana   
4  10, 3rd Floor, Lakshmi Associates, Gandhi Baza...          Grand Village   

  online_order book_table   rate  votes                             phone  \
0          Yes        Yes  4.1/5    775    080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5    787                      080 41714161   
2          Yes         No  3.8/5    918                    +91 9663487993   
3           No         No  3.7/5     88                    +91 9620009302   
4           No         No  3.8/5    166  +91 8026612447\r\n+91 9901210005   

       location            rest_type  \
0  Banashankari        Casual Dining   
1  Banashankari        Casual Dining   
2  Banashankari  Cafe, Casual Dining   
3  Banashankari          Quick Bites   
4  Basavanagudi        Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...   
3                                        Masala Dosa   
4                                Panipuri, Gol Gappe   

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                     '800.0'   
1     Chinese, North Indian, Thai                     '800.0'   
2          Cafe, Mexican, Italian                     '800.0'   
3      South Indian, North Indian                     '300.0'   
4        North Indian, Rajasthani                     '600.0'   

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []   
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []   
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []   
3  [('Rated 4.0', "RATED\n  Great food and proper...        []   
4  [('Rated 4.0', 'RATED\n  Very good restaurant ...        []   

  listed_in(type) listed_in(city)  
0          Buffet    Banashankari  
1          Buffet    Banashankari  
2          Buffet    Banashankari  
3          Buffet    Banashankari  
4          Buffet    Banashankari

Pandas  dataframe are very well labled.
The head function displays the top 5(default) entries.
We can update the number of data rows printed as a param to head.

df.head(10) will display the top 10 rows.

|||ly, we also have df.tail() which will, by default, the last 5 rows and can be updated to print the last <param> number of rows, by passing param to tail.


df.shape : gives the shape of df.


```
df.shape

(23193,17)
```



In [11]:
df.shape

(23193, 17)

df.info() function provides very important information regarding the dataset.
For example, in this case, its providing us with info such as the order and names of the columns, number of non-null entries, count and the data-type.


IMPORTANT : OBJECT seen here is not an Oops object. The name of the datatype is Object.

Object is a composit object. ie it can be of any datatype. It can be a string, a dictionary or even a custom dsatastructure.

```
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

```

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64 
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23

In [13]:
#SQL equivalent of select operation :
# We can use the square brackets or the dot operator.
df['address']
df.address

#Data type of the value at address :
print(type(df['address']))

#If we want to display a specific column eg column 4, we can do :
print(df['address'][4])


# If we want to display multiple columns, then we can make a list of all the
# columns and treat it as a separate array. eg, display address and rate

print(df[['address', 'rate']])

# This is equivalent of creating a smaller dataframe from another dataframe.
# This is because we can select multiple columns and muliple types. So its a dataframe.
print(type(df[['address', 'rate']]))


<class 'pandas.core.series.Series'>
10, 3rd Floor, Lakshmi Associates, Gandhi Bazaar Main Road, Above Reliance Trends, Basavanagudi, Bangalore
                                                 address    rate
0      942, 21st Main Road, 2nd Stage, Banashankari, ...   4.1/5
1      2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...   4.1/5
2      1112, Next to KIMS Medical College, 17th Cross...   3.8/5
3      1st Floor, Annakuteera, 3rd Stage, Banashankar...   3.7/5
4      10, 3rd Floor, Lakshmi Associates, Gandhi Baza...   3.8/5
...                                                  ...     ...
23188  2nd Floor, Iona, Virginia Mall, Whitefield Mai...  3.8 /5
23189  Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...  3.9 /5
23190  Keys Hotel, 6, 1st Phase Industrial Area, Near...  2.8 /5
23191  139/C1, Next To GR Tech Park, Pattandur Agraha...  2.5 /5
23192  Sheraton Grand Bengaluru Whitefield Hotel & Co...  4.3 /5

[23193 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


# Dataframe and Series

A dataframe is a grouping of one or more columns.
Individually, each column is called a series. Series is nothing more than a 1D numpy Array.

In [27]:
data = {
    "Resturant": ["R1", "R2", "R3"],
    "Votes": [120, 240, 150],
    "Rating": [4.1, 4.5, 3.9]
}

resturant_df = pd.DataFrame(data)
resturant_df

Resturant  Votes  Rating
0        R1    120     4.1
1        R2    240     4.5
2        R3    150     3.9

In [28]:
print(resturant_df)
resturant_df.rename(columns={'Votes':'Total_Votes'})

  Resturant  Votes  Rating
0        R1    120     4.1
1        R2    240     4.5
2        R3    150     3.9


Resturant  Total_Votes  Rating
0        R1          120     4.1
1        R2          240     4.5
2        R3          150     3.9

When we rename, it creates a new dataframe, but we have to store it back to original frame.

In [29]:
print(resturant_df)
resturant_df = resturant_df.rename(columns={'Votes':'Total_Voltes'})
print(resturant_df)

  Resturant  Votes  Rating
0        R1    120     4.1
1        R2    240     4.5
2        R3    150     3.9
  Resturant  Total_Voltes  Rating
0        R1           120     4.1
1        R2           240     4.5
2        R3           150     3.9


In [37]:
df.head()

url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...   
1  https://www.zomato.com/bangalore/spice-elephan...   
2  https://www.zomato.com/SanchurroBangalore?cont...   
3  https://www.zomato.com/bangalore/addhuri-udupi...   
4  https://www.zomato.com/bangalore/grand-village...   

                                             address                   name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...                  Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...         Spice Elephant   
2  1112, Next to KIMS Medical College, 17th Cross...        San Churro Cafe   
3  1st Floor, Annakuteera, 3rd Stage, Banashankar...  Addhuri Udupi Bhojana   
4  10, 3rd Floor, Lakshmi Associates, Gandhi Baza...          Grand Village   

  online_order book_table   rate  votes                             phone  \
0          Yes        Yes  4.1/5    775    080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5    787                      080 41714161   
2          Yes         No  3.8/5    918                    +91 9663487993   
3           No         No  3.7/5     88                    +91 9620009302   
4           No         No  3.8/5    166  +91 8026612447\r\n+91 9901210005   

       location            rest_type  \
0  Banashankari        Casual Dining   
1  Banashankari        Casual Dining   
2  Banashankari  Cafe, Casual Dining   
3  Banashankari          Quick Bites   
4  Basavanagudi        Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...   
3                                        Masala Dosa   
4                                Panipuri, Gol Gappe   

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                     '800.0'   
1     Chinese, North Indian, Thai                     '800.0'   
2          Cafe, Mexican, Italian                     '800.0'   
3      South Indian, North Indian                     '300.0'   
4        North Indian, Rajasthani                     '600.0'   

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []   
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []   
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []   
3  [('Rated 4.0', "RATED\n  Great food and proper...        []   
4  [('Rated 4.0', 'RATED\n  Very good restaurant ...        []   

  listed_in(type) listed_in(city)  
0          Buffet    Banashankari  
1          Buffet    Banashankari  
2          Buffet    Banashankari  
3          Buffet    Banashankari  
4          Buffet    Banashankari

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64 
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23

In [40]:
df['rate']

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...  
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

#On Strings in python, we can apply slicing logic

In [44]:
#Non vectorized way to do the action
df['only_rating'] =[i[:-2] for i in df['rate']]
df['only_rating']

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ... 
23188    3.8 
23189    3.9 
23190    2.8 
23191    2.5 
23192    4.3 
Name: only_rating, Length: 23193, dtype: object

In [57]:
#df = df.rename(columns={'votes':'Total_Votes'})
df['Total_Votes_div100'] = df['Total_Votes']/100
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23193 entries, 0 to 23192
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   url                          23193 non-null  object 
 1   address                      23193 non-null  object 
 2   name                         23193 non-null  object 
 3   online_order                 23193 non-null  object 
 4   book_table                   23193 non-null  object 
 5   rate                         23193 non-null  object 
 6   Total_Votes                  23193 non-null  int64  
 7   phone                        23193 non-null  object 
 8   location                     23193 non-null  object 
 9   rest_type                    23193 non-null  object 
 10  dish_liked                   23193 non-null  object 
 11  cuisines                     23193 non-null  object 
 12  approx_cost(for two people)  23193 non-null  object 
 13  reviews_list         

In [61]:
np.where(df['Total_Votes']>500,'Good','Bad')
#df.info()

array(['Good', 'Good', 'Good', ..., 'Bad', 'Bad', 'Bad'], dtype='<U4')

In [67]:
#unique() provides us all the unique values
df['cuisines'].unique()
#Provides us the total number of unique values.
df['cuisines'].nunique()

1687

In [74]:
# value_counts() Provides us the total number of unique
# resturant types available in the reverse sorted order.
# ie, this is equivalent to group_by in SQL for counting.
df['rest_type'].value_counts()

# normalize=True gives us the ratio of count to the total count.
df['rest_type'].value_counts(normalize=True)

# Multiple by 100 to get %
df['rest_type'].value_counts(normalize=True) * 100

rest_type
Casual Dining                31.686285
Quick Bites                  22.593024
Cafe                         10.024576
Dessert Parlor                4.639331
Casual Dining, Bar            4.242659
                               ...    
Fine Dining, Microbrewery     0.021558
Club, Casual Dining           0.017247
Dessert Parlor, Kiosk         0.008623
Dhaba                         0.004312
Food Court, Casual Dining     0.004312
Name: proportion, Length: 73, dtype: float64